apiVersion: v1
kind: Secret
metadata:
  name: timeazon-api-secrets
type: Opaque
stringData:
  CLUSTER_ARN: "PASTE_CLUSTER_ARN"
  SECRET_ARN: "PASTE_SECRET_ARN"

# Will note, you will have to update the CLUSTER_ARN and SECRET_ARN with the values used in your EC2 .env
